{
  "formatVersion": "1.1",
  "component": {
    "group": "net.nikdo53",
    "module": "NeoBackports",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "NeoBackports-1.2.2-accesstransformer.cfg",
          "url": "NeoBackports-1.2.2-accesstransformer.cfg",
          "size": 1020,
          "sha512": "d61eb72f2f99d6fce657e7343538bc7fc482b57b07e444987548e6e4af6669187549dd996d485e81a9383ff618ccad7807cfd16218ef1ea09ded842e9a59a96f",
          "sha256": "f9930b0e78eb5a14280d5ba77afe4c64d6835a854e04a8a2b86d021e7be14c53",
          "sha1": "19f3577e68f2714716aa8facd44d357ee0dca6f1",
          "md5": "70979a0931e3759b46f3caece1849bd1"
        }
      ]
    },
    {
      "name": "interfaceInjectionDataElements",
      "attributes": {
        "org.gradle.category": "interfaceinjection"
      },
      "files": [
        {
          "name": "NeoBackports-1.2.2-interfaceinjection.json",
          "url": "NeoBackports-1.2.2-interfaceinjection.json",
          "size": 3632,
          "sha512": "11f78ab57bd7565db9e6fc5cd1659e4fde1313ea24e7cc52fdf7499d3833a029cf471110dfcf59dce6c67f124ed0eeed7d07efc11cfb0749c8abbbe593ab2f1c",
          "sha256": "8d9bd71178d5e9e02984ff33119cff79fa208f752e8a58e32ae62d981098cc67",
          "sha1": "5d67285d51c6b2baede8a0654df7edd4e34571a9",
          "md5": "274a65ab1e8a5a8b2f8d10ce8599209c"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.2.2.jar",
          "url": "NeoBackports-1.2.2.jar",
          "size": 1063761,
          "sha512": "a777f5d32ee109047d1aefeb3a44edd3d2c0311e7b96a6dd51aaaf810239a0d55971af2e8beb0e435c0f3d05e83f8a1460e40e6bb1de3ad514781e05a6f60a5e",
          "sha256": "7fee556410948ff599c547ccba100f43e248624f643a31ed8d44738ac7307a19",
          "sha1": "c52f46acbfcc44637d46d8605647b2aadce09edb",
          "md5": "04a7d74bb5934b3cfc20009d0aca4a3e"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NeoBackports-1.2.2.jar",
          "url": "NeoBackports-1.2.2.jar",
          "size": 1063761,
          "sha512": "a777f5d32ee109047d1aefeb3a44edd3d2c0311e7b96a6dd51aaaf810239a0d55971af2e8beb0e435c0f3d05e83f8a1460e40e6bb1de3ad514781e05a6f60a5e",
          "sha256": "7fee556410948ff599c547ccba100f43e248624f643a31ed8d44738ac7307a19",
          "sha1": "c52f46acbfcc44637d46d8605647b2aadce09edb",
          "md5": "04a7d74bb5934b3cfc20009d0aca4a3e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.2.2-javadoc.jar",
          "url": "NeoBackports-1.2.2-javadoc.jar",
          "size": 878447,
          "sha512": "dc967d1bfe86a526931fefaf3b0fc94029c7426cf5c67ee42e89e0875d8ed26d57431c6fe4c008f173d1342b6ee9a4cb5f8c5fa0645f637f3d4bb8fbf254d67a",
          "sha256": "b686da219fe84e8e5bec705965d86eb3c11acf6026363226c1a384e429116849",
          "sha1": "9bdc313f91c44824d39cc3612f2d739319262894",
          "md5": "bedff96319d69abf4f626d051c5bccfd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeoBackports-1.2.2-sources.jar",
          "url": "NeoBackports-1.2.2-sources.jar",
          "size": 181235,
          "sha512": "7a806ead18a02be6a5187a948ae6ccb19df9c1e49c617a53738ca0eb7daac7c6ada9b0df623b0a131398cd35265f37da8db40f9553d625b6cdba9b88cdcce620",
          "sha256": "7f85095ebcdf08d2e167d338c67d22b2bd942e6fb9f2ffcb5d5ab32199958d1f",
          "sha1": "f82a332b0819e7f36e98afaac715eb7e3ea96b74",
          "md5": "c0a06ccaa8be8c46ffcb9d27b42c6c6e"
        }
      ]
    }
  ]
}
